apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      name: sonar
      labels:
        app: sonar
    spec:
      containers:
        - image: sonarqube:6.0
          args:
            - -Dsonar.web.context=/
          name: sonar
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-info
                  key: password
            - name: SONARQUBE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: db-info
                  key: url 
          ports:
            - containerPort: 9000
              name: sonar
