kind: Service
apiVersion: v1
metadata:
  name: sonar-service
spec:
  selector:
    run: sonar-service
  ports:
    - name: port1
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: port2
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
